### ISSUE TITLE
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 7

### ISSUE THREAD

**Issue by niemasd** [PangeaHIV/VirusTreeSimulator#1]
I downloaded the VirusTreeSimulator.jar file and tried running it with the example data as follows:

`java -jar VirusTreeSimulator.jar -N0 100 -growthRate 10 -t50 10 inf_test.csv samp_test.csv test`

and I get the following error:

```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 7
	at TransmissionTreeToVirusTree.readSamplingEvents(TransmissionTreeToVirusTree.java:178)
	at TransmissionTreeToVirusTree.<init>(TransmissionTreeToVirusTree.java:72)
	at TransmissionTreeToVirusTree.main(TransmissionTreeToVirusTree.java:620)
```

The error is the same even if I use default parameters:

`java -jar VirusTreeSimulator.jar inf_test.csv samp_test.csv test`

**Comment by niemasd** [comment]
Unfortunately no, sorry!

**Comment by niemasd** [comment]
No, this is a separate tool developed by independent folks that I happen to wrap around in FAVITES. I'm not affiliated with this tool's development

**Comment by mdhall272** [comment]
Is this working? I'm not sure if there's a current error.

**Comment by mdhall272** [comment]
Yes. Does your transmission tree have multiple index cases?

**Comment by mdhall272** [comment]
Right. Well, that's output. Sometimes you get more trees than you would expect if there was an incomplete bottleneck simulated in the index case.

**Comment by mdhall272** [comment]
The `-forceCoalescence` flag. If it's there then all bottlenecks are complete. I think this is best avoided because all it does is truncate the distribution of coalescence times. Even if the WH host model makes it extremely unlikely that all lineages would coalesce before (in backwards time) infection, the simulation will make it so. Better to select a WH function that makes it extremely unlikely but possible.

**Comment by liamxg** [comment]
@mdhall272 thanks for your reply.

**Comment by liamxg** [comment]
Building tree(s) for descendants of ID_charlie
WARNING: any phylogeny for descendants of ID_charlie is quite improbable (p<9.97503330210369E-16) given this demographic function. Consider another.

Building tree(s) for descendants of ID_lima
WARNING: any phylogeny for descendants of ID_lima is quite improbable (p<9.99000583083359E-7) given this demographic function. Consider another.

**Comment by liamxg** [comment]
what does WH function mean? @mdhall272
