### ISSUE TITLE
java.io.FileNotFoundException: ID_79882_simple.nex (Too many open files)

### ISSUE THREAD

**Issue by niemasd** [PangeaHIV/VirusTreeSimulator#2]
I am getting the following error when running on a large dataset:

```bash
-bash-4.1$ java.io.FileNotFoundException: ID_79882_simple.nex (Too many open files)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(FileOutputStream.java:270)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:101)
        at java.io.PrintStream.<init>(PrintStream.java:208)
        at TransmissionTreeToVirusTree3.run(TransmissionTreeToVirusTree3.java:122)
        at TransmissionTreeToVirusTree3.main(TransmissionTreeToVirusTree3.java:684)
```

My guess is that, on [line 121 of TransmissionTreeToVirusTree3.java](https://github.com/PangeaHIV/VirusTreeSimulator/blob/master/src/TransmissionTreeToVirusTree3.java#L121), all of the `PrintStream` objects that are being spawned are not being closed. My guess is that you should add a statement to close each `PrintStream` object after its export is complete

**Comment by niemasd** [comment]
Fixed and created a merge request: https://github.com/PangeaHIV/VirusTreeSimulator/pull/3

**Comment by niemasd** [comment]
Never mind, still getting the error. No clue why

**Comment by mdhall272** [comment]
I can have a look - is there an example dataset you could send me?

**Comment by niemasd** [comment]
No worries, I tried running it on another cluster and it worked fine. The one I ran it on originally is extremely restrictive, so I'm guessing it has something to do with unnaturally low restrictions on file I/O they place. Thank you, though!
